# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8c95819804e7cbaf8be07deebf4e505e6f8dd7fa35c409e222915439c89992d50b55b2d86c9c3ba3ddfa68ac5380d6bd78472fcc8cd27a6497bc6fe0e4a37fc

test:
  secret_key_base: 86ad083c9bb59ae6a225c8de1d607001b837772c3d5f7b998f0e9a276a8afc7649dff096ec4763267176690065898c7b48b3efa1b73536f1102b02da09801fc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
